import Head from 'next/head';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { useAdditionalLinks } from '~/shared/hooks/useAdditionalLinks';

export default function Home() {
  const additionalLinks = useAdditionalLinks();
  const [prerendering, setPrerendering] = useState('ssg');
  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{textAlign: 'center', padding: 20}}>
          <label htmlFor="prere" style={{padding: 10}}>Prerendering</label>
          <select id="prere" onChange={(evt) => setPrerendering(evt.currentTarget.value)}>
            <option value="ssg">SSG</option>
            <option value="ssr">SSR</option>
          </select>
        </div>
        <h1 style={{ paddingBottom: '10px' }}>Profili Github</h1>
        <div style={{ display: 'flex', flexFlow: 'column', gap: 10 }}>
          <Link href={`/${prerendering}/irsooti`}>Daniele</Link>
          <Link href={`/${prerendering}/Giovanna10`}>Giovanna</Link>
          <Link href={`/${prerendering}/ironkiller86`}>Donato</Link>
          {additionalLinks.map((link) => (
            <Link key={link.url} href={`/${prerendering}/${link.url}`}>
              {link.label}
            </Link>
          ))}
        </div>
      </main>
    </>
  );
}
