import Head from 'next/head';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';

export default function Home() {
  const [moreLinks, setMoreLinks] = useState<{ label: string; url: string }[]>(
    []
  );

  useEffect(() => {
    setTimeout(() => {
      setMoreLinks([{ label: 'Luca', url: '/ssg/morriconeluca' }]);
    }, 1000);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 style={{ paddingBottom: '10px' }}>Profili Github</h1>
        <div style={{ display: 'flex', flexFlow: 'column', gap: 10 }}>
          <Link href="/ssg/irsooti">Daniele</Link>
          <Link href="/ssg/Giovanna10">Giovanna</Link>
          {moreLinks.map((link) => (
            <Link key={link.url} href={link.url}>
              {link.label}
            </Link>
          ))}
        </div>
      </main>
    </>
  );
}
